//
//
// Copyright 2021 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: testserver.proto

package testserver

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the user's name.
type MessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       string                 `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageRequest) Reset() {
	*x = MessageRequest{}
	mi := &file_testserver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageRequest) ProtoMessage() {}

func (x *MessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_testserver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageRequest.ProtoReflect.Descriptor instead.
func (*MessageRequest) Descriptor() ([]byte, []int) {
	return file_testserver_proto_rawDescGZIP(), []int{0}
}

func (x *MessageRequest) GetRequest() string {
	if x != nil {
		return x.Request
	}
	return ""
}

// The response message containing the greetings
type MessageReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      string                 `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageReply) Reset() {
	*x = MessageReply{}
	mi := &file_testserver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageReply) ProtoMessage() {}

func (x *MessageReply) ProtoReflect() protoreflect.Message {
	mi := &file_testserver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageReply.ProtoReflect.Descriptor instead.
func (*MessageReply) Descriptor() ([]byte, []int) {
	return file_testserver_proto_rawDescGZIP(), []int{1}
}

func (x *MessageReply) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

var File_testserver_proto protoreflect.FileDescriptor

const file_testserver_proto_rawDesc = "" +
	"\n" +
	"\x10testserver.proto\x12\n" +
	"helloworld\"*\n" +
	"\x0eMessageRequest\x12\x18\n" +
	"\arequest\x18\x01 \x01(\tR\arequest\"*\n" +
	"\fMessageReply\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\tR\bresponse2S\n" +
	"\n" +
	"TestServer\x12E\n" +
	"\vSendMessage\x12\x1a.helloworld.MessageRequest\x1a\x18.helloworld.MessageReply\"\x00B\x15Z\x13internal/testserverb\x06proto3"

var (
	file_testserver_proto_rawDescOnce sync.Once
	file_testserver_proto_rawDescData []byte
)

func file_testserver_proto_rawDescGZIP() []byte {
	file_testserver_proto_rawDescOnce.Do(func() {
		file_testserver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_testserver_proto_rawDesc), len(file_testserver_proto_rawDesc)))
	})
	return file_testserver_proto_rawDescData
}

var file_testserver_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_testserver_proto_goTypes = []any{
	(*MessageRequest)(nil), // 0: helloworld.MessageRequest
	(*MessageReply)(nil),   // 1: helloworld.MessageReply
}
var file_testserver_proto_depIdxs = []int32{
	0, // 0: helloworld.TestServer.SendMessage:input_type -> helloworld.MessageRequest
	1, // 1: helloworld.TestServer.SendMessage:output_type -> helloworld.MessageReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_testserver_proto_init() }
func file_testserver_proto_init() {
	if File_testserver_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_testserver_proto_rawDesc), len(file_testserver_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_testserver_proto_goTypes,
		DependencyIndexes: file_testserver_proto_depIdxs,
		MessageInfos:      file_testserver_proto_msgTypes,
	}.Build()
	File_testserver_proto = out.File
	file_testserver_proto_goTypes = nil
	file_testserver_proto_depIdxs = nil
}
